language: node_js
node_js:
  - "12"
dist: bionic
addons:
  - chrome: stable
# install: "npm install"
script: "sh -e run_tests.sh"
after_success:
  - "if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then ./ci-deploy.sh; fi"
